---
all:
  children:
    production:
      hosts:
        cyclops:
    testing:
      hosts:
        tcyclops:
          ansible_host: 192.168.1.2
    proxmox:
      hosts:
        cyclops:
        tcyclops:
