---
- name: Check If Already Patched
  ansible.builtin.command:
    cmd: grep -c "res.data.status.toLowerCase() !== 'active'" /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
  register: no_sub_popup_patch_check
  changed_when: false
  failed_when: false
- name: Patch `proxmoxlib.js` to Suppress No-Subscription Popup
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: res\.data\.status\.toLowerCase\(\) !== 'active'
    replace: "false"
    backup: true
  when: no_sub_popup_patch_check.stdout | int > 0
  notify: Restart `pveproxy` Service
