[global]
keyboard = "en-us"
country = "za"
fqdn = "tcyclops.zezura.cc"
mailto = "admin@tcyclops.zezura.cc"
timezone = "Africa/Johannesburg"
root-password = "password"
reboot-mode = "power-off"

[network]
source = "from-answer"
cidr = "10.0.0.2/24"
dns = "1.1.1.1"
gateway = "10.0.0.1"
filter.ID_NET_NAME = "eth0"

[disk-setup]
filesystem = "ext4"
disk-list = ["sda"]
