---
- name: Configure Proxmox
  hosts: proxmox
  gather_facts: false
  roles: [proxmox]
- name: Configure Firewall
  hosts: proxmox
  gather_facts: false
  roles: [firewall]
- name: Configure Fail2Ban
  hosts: proxmox
  gather_facts: false
  roles: [fail2ban]
